default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-wikinimous_development

test:
  <<: *default
  database: rails-wikinimous_test

production:
  <<: *default
  database: rails-wikinimous_production
  username: rails-wikinimous
